services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  FastRoute\RouteParser:
    class: FastRoute\RouteParser\Std

  FastRoute\DataGenerator:
    class: FastRoute\DataGenerator\GroupCountBased

  route_collector:
    class: IA\Route\Collector\RouteCollector

  IA\Route\Collector\RouteCollectorInterface:
    alias: route_collector

  FastRoute\RouteCollector:
    alias: route_collector

  route_resolver:
    class: IA\Route\Resolver\RouteResolver
    arguments:
      $debug: '%kernel.debug%'
      $cacheDir: '%kernel.cache_dir%'
      $handlerDirs:
        - '%kernel.project_dir%/src/Controller'

  IA\Route\Resolver\RouteResolverInterface:
    alias: route_resolver

  route_url_generator:
    class: IA\Route\Generator\UrlGenerator

  IA\Route\Generator\UrlGeneratorInterface:
    alias: route_url_generator

  IA\Route\RouteMiddleware: ~

  App\Middleware\RouteMiddleware: ~
